{
 "title": "LLM Monitoring Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Label Distributions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "injection/safe labels",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(CASE WHEN prompt_label = 'injection' THEN 1 END) AS injection_count, COUNT(CASE WHEN prompt_label = 'safe' THEN 1 END) AS safe_count FROM benchmark_llm_monitoring"
    }
   ]
  },
  {
   "title": "harm/safe labels",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(CASE WHEN response_label = 'harm' THEN 1 END) AS harm_count, COUNT(CASE WHEN response_label = 'safe' THEN 1 END) AS safe_count FROM benchmark_llm_monitoring"
    }
   ]
  },
  {
   "title": "refusal/compliance labels",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(CASE WHEN response_refusal_label = 'refusal' THEN 1 END) AS refusal_count, COUNT(CASE WHEN response_refusal_label = 'compliance' THEN 1 END) AS compliance_count FROM benchmark_llm_monitoring"
    }
   ]
  },
  { "title": "Metrics ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "WITH f1_data AS (SELECT 'prompt_label | injection'  AS label, 1.0 AS precision, 0.4268104776579353 AS recall, 0.5982721382289417 AS f1\n  UNION ALL SELECT 'prompt_label | safe'        AS label, 0.3059701492537313 AS precision, 1.0 AS recall, 0.4685714285714286 AS f1\n  UNION ALL SELECT 'refusal_label | refusal'    AS label, 0.5362318840579711 AS precision, 0.902439024390244 AS recall, 0.9762532981530344 AS f1\n  UNION ALL SELECT 'refusal_label | compliance' AS label, 0.9946236559139784 AS precision, 0.9585492227979274 AS recall, 0.6727272727272727 AS f1\n  UNION ALL SELECT 'response_label | harm'      AS label, 0.9534883720930232 AS precision, 0.2128027681660899 AS recall, 0.347949080622348  AS f1\n  UNION ALL SELECT 'response_label | safe'      AS label, 0.3347953216374269 AS precision, 0.9744680851063828 AS recall, 0.4983677910772578 AS f1\n)\nSELECT label, precision, recall, f1 FROM f1_data;"
    }
   ]
  },
  {
   "title": "Prompt Length Distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT CONCAT(FLOOR(LENGTH(prompt) / 10) * 10, '-', FLOOR(LENGTH(prompt) / 10) * 10 + 9) AS \"range\", COUNT(*) AS count FROM benchmark_llm_monitoring GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Response Length Distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT CONCAT(FLOOR(LENGTH(response) / 10) * 10, '-', FLOOR(LENGTH(response) / 10) * 10 + 9) AS \"range\", COUNT(*) AS count FROM benchmark_llm_monitoring GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Benchmark LLM Monitoring",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT * FROM benchmark_llm_monitoring ORDER BY id LIMIT 100;"
    }
   ]
  }
 ]
}